describe('pizza-dominos', () => {
  it('comprar-pizza-dominos', () => {
    cy.visit('https://www.dominos.com.br/')
    cy.get("[data-method='Carryout']").click()
    cy.get('.js-noCep').click()
    cy.get('#Region').select('SP')
    cy.get('#City').select('SÃO PAULO')
    cy.get("[type='submit']").click()
    cy.get("[data-quid='locations-search-19572-order-carryout-button']").click()
    cy.get('#entree-Pizza').click()
    cy.get("[data-dpz-track-evt-name='Order CTA | Monte sua Pizza']").click()
    cy.get('[data-quid="builder-topping-P-text"] > input')
    cy.get('.pizza-topping__weight').eq(2).select('Normal')
    cy.get('.single-page-pizza-builder__add-to-order').click()
    cy.get('.btn--no-thanks').click()
    cy.get('.btn--checkout').click()
    cy.get('.js-nothanks').click()
    cy.get('.js-removeVariant').click()
  })
})